language: r
cache: packages

r:
  - release

r_github_packages:
  - rstudio/DT

notifications:
  email:
    on_success: change
    on_failure: change

## Only run covr on release
#after_success:
#  - Rscript -e "if(length(grep('2\$', ${TRAVIS_JOB_NUMBER}))) covr::codecov()";
